pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f /var/lib/jenkins/workspace/Package_Application_Code_Pipeline/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{

                build job: 'Deploy_Application_staging'



            }
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_Application_Prod'
            }
        }
    }
}
